#!/bin/bash

set -ex

# set LOAD_URL to the proper color in production, run directly against url in stage
if [ -n "$PRODUCTION" ]; then
export NEXT_APP_COLOR=$(cat ./current-app-info/next-app.txt)
export LOAD_URL=$NEXT_APP_COLOR-$PCF_APP_SUFFIX.$PCF_APP_DOMAIN/
else
export LOAD_URL=$PCF_APP_SUFFIX.$PCF_APP_DOMAIN/
fi

echo "Running jmeter load tests against $LOAD_URL..."

#artillery quick --duration 10 --rate 10 $NEXT_APP_URL
#artillery run -t $LOAD_URL ./PivotalDevOpsTutorial/ci/tasks/artillery-script.yml
# execute jmeter script
jmeter -Dduration=30 -Dhostname=$LOAD_URL -n -t ./$APP_REPO/test/load/get_endpoints.jmx
